[package]
name = "litec_lower"
version = "0.1.0"
edition = "2024"

[dependencies]
litec_ast = { path = "../litec_ast" }
litec_hir = { path = "../litec_hir" }
litec_span = { path = "../litec_span" }
litec_errors = { path = "../litec_errors"}

[lib]